export declare const ALLOWED_EXTENSIONS: string[];
export declare const NEXT_FILES: string[];
export declare const FALLBACK_BASE_URL = "http://localhost:3000";
export declare const NODE_SIZE = 160;
export declare const NODE_SPACING_X = 160;
export declare const NODE_SPACING_Y = 160;
export declare const NODE_WIDTH = 160;
export declare const NODE_HEIGHT = 160;
export declare const NODE_BORDER = 2;
export declare const NODE_BORDER_RADIUS = 10;
export declare const HANDLE_SIZE = 5;
